openapi: 3.0.0
info:
  version: 0.0.1
  title: DataCanvas Service
tags:
  - name: DataCanvas
schemes:
  - https
servers:
  - url: https://api.pennsieve.io/datacanvas
  - url: https://api.pennsieve.net/datacanvas

paths:
  /health:
    get:
      security: []
      summary: healthcheck
      operationId: healthcheck
      x-scala-package: healthcheck
      description: Ensure the service is responding to requests.
      responses:
        '200':
          description: Success
