swagger: '2.0'
info:
  version: 0.0.0
  title: 'DataCanvas Service'
host: 0.0.0.0:8080
schemes:
  - https
tags:
  - name: DataCanvas
securityDefinitions:
  Bearer:
    type: apiKey
    in: header
    name: Authorization
paths:
  /health:
    get:
      security: []
      summary: healthcheck
      operationId: healthcheck
      x-scala-package: healthcheck
      description: Ensure the service is responding to requests.
      responses:
        200:
          description: Success
  /canvas/{organizationId}/{datacanvasId}:
    get:
      summary: get a DataCanvas by id
      security:
        - Bearer: [ ]
      operationId: getById
      x-scala-package: datacanvas
      parameters:
        - name: organizationId
          in: path
          description: organization id
          required: true
          type: integer
          format: int32
        - name: datacanvasId
          in: path
          description: datacanvas id
          required: true
          type: integer
          format: int32
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            type: object
            x-scala-type: com.pennsieve.datacanvas.models.DatacanvasDTO
        401:
          description: Unauthorized
        403:
          description: Forbidden
          schema:
            type: string
        404:
          description: resource not found
          schema:
            type: string
        500:
          description: Internal error
          schema:
            type: string
